# load necessary packages

library(rmarkdown)
library(RSelenium)
library(rvest)
library(RMySQL)
library(stringr)
library(tidytext)
library(tinytex)
library(tidyr)
library(dplyr)
library(ggplot2)
library(beepr)
library(tidyverse)
library(jsonlite)
library(httr)
library(magick)
library(rtweet)
library(wordcloud)
library(MASS)
library(textdata)